### ISSUE TITLE
Hangs during boot process

### ISSUE THREAD

**Issue by imThief** [a1ive/ntloader#1]
Hi!
Have tried your image with gnu grub2, download/compile - all looks nice, but during boot after message "Installing block I/O protocol for virtual partition..." hangs completely :(. Can you please advice in wich direction to dig? Maybe some parameter exists to make output more verbose... Thanks!
P.S. Any info you need - just ask.
![image](https://user-images.githubusercontent.com/39994745/107164626-f0d41400-69c0-11eb-88d1-d44f32dece41.png)

**Comment by a1ive** [comment]
Please try this: 
[ntloader.tar.gz](https://github.com/a1ive/ntloader/files/5940737/ntloader.tar.gz)

**Comment by imThief** [comment]
Now works great, thanks! Booted from raw fat32 partition without any problems (Win PE environment), from iso loopback - too (but further boot has been halted - BCD couldn't find source partition). Any thoughts about implementing such feature (loopback device boot) btw? Very useful trick, imho. And could you tell me please, does your image can boot wim's from non-fat partition (ntfs or ext2, for example)?

**Comment by a1ive** [comment]
>  from iso loopback - too (but further boot has been halted - BCD couldn't find source partition). Any thoughts about implementing such feature (loopback device boot) btw?

The partition where the WIM/VHD is located must be accessible by Windows/bootmgr, otherwise you can only use `ipxe wimboot` (GNU GRUB2 does not support booting wimboot under UEFI).

For WIM files, you can boot them from FAT32, exFAT & NTFS.
For VHD files, you can boot them from NTFS & exFAT (Win 10 1809+).

**Comment by imThief** [comment]
All clear, many thanks for the help!

**Comment by imThief** [comment]
Unfortunately it cannot boot from exFAT or NTFS (i assume because BCD doesn't support both)

**Comment by a1ive** [comment]
If you boot it with GNU GRUB 2, you need to put the `ntloader` and `initrd.lz1` files in the same FAT partition.
